/* 
export { default as  About } from "./about"
export { default as  AssetDetails } from "./asset-details"
export { default as  Assets} from "./assets"
export { default as  BecomeBusiness} from "./become-business"
export { default as  BecomeCreative} from "./become-creative"
export { default as  BusinessDetail} from "./business-details"
export { default as  Business} from "./business"
export { default as  SignUp} from "./signup"
export { default as  Login} from "./login"
export { default as  Creative} from "./creative"
export { default as  Faq} from "./faq"
export { default as  Gallery} from "./gallery"
export { default as  Index2} from "./index-2"
export { default as  Index3} from "./index-3" */
export { default as  Welcome} from "./HomePage"
export { default as  BecomeBusiness} from "./become-business"
export { default as  Index2} from "./index-2"
export { default as  SingUp} from "./signup"
export { default as  Login} from "./login"
export { default as  BecomeCreador} from "./become-creative"
export { default as  AssetsPage} from "./assets"
export { default as  Colections} from "./colections"
export { default as  AssetPublicar} from "./faq"
/* export { default as  Pricing} from "./pricing"
export { default as  PromoDetail} from "./promo-details"
export { default as  Promos} from "./promos"
 */
